---
abstract: 'UserAgent based on libcurl'
author:
  - 'Julian Knocke'
  - 'Othello Maurer'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Curl-UserAgent
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=WWW-Curl-UserAgent
  homepage: https://github.com/xing/curl-useragent/wiki
  repository: git://github.com/xing/curl-useragent.git
version: 0.9.1
